name: Unquoted Branch Name Injection PoC

on:
  pull_request_target:
    types: [synchronize] # 严格保留 synchronize 触发器
    branches:
      - '**'

jobs:
  test-injection:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        uses: mdecoleman/pr-branch-name@1.2.0
        id: vars
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Vulnerable Sink
        # 🚨 致命缺陷：没有引号，直接裸奔插值
        run: echo ${{ steps.vars.outputs.branch }}
